### ISSUE TITLE
Energy Change Node update

### ISSUE THREAD

**Issue by Sc00bs110** [jacauc/SunSynk-NodeRed#2]
Energy change node needs to be updated for the latest HA update
![image](https://user-images.githubusercontent.com/63442834/132304079-c9b1c86f-b157-4418-b909-465648316131.png)

**Comment by jacauc** [comment]
This was committed a few days ago. Is it not showing up?

**Comment by jacauc** [comment]
Pushed update to master. Issue should be closed now. Please revert if not.

**Comment by Sc00bs110** [comment]
Yes, is sorted now
